packages:
  - "app"
  - "browser"
allowBuilds:
  '@clerk/shared': true
  '@parcel/watcher': true
  '@swc/core': true
  browser-tabs-lock: true
  bufferutil: true
  core-js: true
  esbuild: true
  sharp: true
  utf-8-validate: true
  workerd: true
